### ISSUE TITLE
roadmap: features required for initial release

### ISSUE THREAD

**Issue by jimmyl02** [redpwn/rvpn#10]
hard feature requirements:
- [x] linux source based routing
- [x] heartbeat from client to control plane
  - including reaping of stale connections (last heartbeat over 5 minutes old)
- [ ] support for only serving specific subnets (metadata)
- [x] clients must add specific route for control plane ws to use default interface
  - if not done, tcp socket connection will die
- [x] auth jrpc call from control plane to client instead of immediately sending from client
- [ ] overall polish
  - [x] clean up routes
  - [ ] TODOs in the code
  - [ ] locking for synchronization
  - etc.
- [x] re-enable target server aliveness check
- [ ] proper AuthZ on the control plane for client and serve connections
- [x] verbose error messages to client when something goes wrong
  - daemon should never fatally error (this is going to be a huge refactor)
  - server should never fatally error
- [x] validate elevation
- [ ] frontend implementation

hard release requirements:
- [x] macos client (homebrew? or installation script)
  - if mac client is not feasible in timely manner, spend more effort on UI to add other devices and connections
- [x] windows installer (WiX)
- [x] linux installer (installation script)
