### ISSUE TITLE
roadmap: feature requests

### ISSUE THREAD

**Issue by jimmyl02** [redpwn/rvpn#14]
this issue tracks the feature roadmap of rVPN

- [ ] split tunnel configurations
- [ ] custom SSO integrations
- [ ] generate "connections" [and qr codes] via the web ui
- [ ] key rotation
- [ ] ACLs (ACLs + manual users, ACLs allow users to join profiles themselves)
- [ ] Invite to profile system
- [ ] Private DNS
- [ ] Monitor network activity
- [ ] NAT hole punching for VPN server
- [x] RPC for rvpn state instead of using a file
- [ ] automatic update if newer rvpn version
